### ISSUE TITLE
Can't get overrides to take effect

### ISSUE THREAD

**Issue by cdanielsen** [chrisdothtml/hyper-stylesheet#3]
Hello,

Was attempting to use this package to override a style I don't like that I think is coming from a plugin ([hyper-snazzy](https://github.com/sindresorhus/hyper-snazzy)), but nothing I do seems to override it. Here's my config, any suggestions appreciated:

Machine: Linux VM (Ubuntu 18)
Terminal: Hyper with oh-my-zsh

```
// ~/.hyper.js
...
plugins: ["hyper-snazzy", "git-falcon9", "hyper-stylesheet"],
...
}
```

```
// ~/.hyper.css
* #window */
/* CSS for the window goes here */
/* #css */
body::-webkit-scrollbar-thumb {
  background-color: #5af78e!important;
}

/* #termCSS */
body::-webkit-scrollbar-thumb {
  background-color: #5af78e!important;
}

/* #terminal */
/* CSS for the terminal goes here */
body::-webkit-scrollbar-thumb {
  background-color: #5af78e!important;
}
```

When I reload hyper and use the inspector, I can see the `<style>` element with these css values (see screenshot), but it has no effect on the scrollbar's color. I've attempted more obvious changes like
```
body {
 background: green;
}
```
but those don't seem to take effect either? Figure I must be doing something wrong. Thanks for any suggestions or if I can clarify any setup.

![hyper_capture](https://user-images.githubusercontent.com/8172556/54055627-8269f400-41a2-11e9-9ed9-84f641e7ce1c.PNG)

**Comment by chrisdothtml** [comment]
Looks like instead using the `.xterm-viewport::-webkit-scrollbar-thumb` selector will do what you're trying to do (just in the `/* #window */` section). [This issue comment](https://github.com/zeit/hyper/issues/2526#issuecomment-349958830) was what pointed me in the right direction

**Comment by cdanielsen** [comment]
🎉 🎉 🎉  that was it! Thanks!
